---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
      user: name="{{ Namen }}" state = present groups = wheel
      loop:
        -FC
        -BMG
        -LEV
     # msg: "Hello 1.FC!" 
   
