---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
      msg: "Hello 1.FC!" 
    
  - name: HDas ist mein erstes YML
    
    file:
    path: /tmp/erstesYML.yml
    state: touch
      
