---
- name: Setup Docker-Server
  hosts: localhost
  remote_user: root

  tasks:

  - name: Hello Server
    debug:
      msg: "Hello 1.FC!" 
    

  - name: Hello Variable_a und _b
    debug:
      msg: "addition{{variable_a + variable_b}}" 
